#pragma once
#include <QObject>
#include <QString>
#include <QTimer>
#include <QDateTime>
#include <QVariant>
#include <QByteArray>
#include <QList>
#include <QApplication>
#include <QMainWindow>
#include <QDockWidget>
#include <QMenuBar>
#include <QAction>
#include <QWidget>
#include <QSerialPort>
#include <QTcpSocket>
#include <QtCharts/QChartView>
#include <spdlog/spdlog.h>
#include <array>
#include <chrono>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
